baseurl: http://kasoutsuka.blue/
languageCode: ja
title: 仮想通貨をはじめよう
author: rakuishi
metadataformat: yaml
preservetaxonomynames: true

params:
  description: '仮想通貨好きプログラマ rakuishi が、仮想通貨をこれからはじめるために必要な知識を随時配信。'

related: 
  threshold: 50
  indices: [{name: 'date', weight: 100, pattern: '2006'}]
