baseurl: http://kasoutsuka.blue/
languageCode: ja
title: 仮想通貨をはじめよう
author: rakuishi
metadataformat: yaml
preservetaxonomynames: true

params:
  description: '仮想通貨をこれからはじめる仮想通貨初心者の分からないを解決します！'

related: 
  threshold: 50
  indices: [{name: 'date', weight: 100, pattern: '2006'}]

sitemap:
  changefreq: daily
  priority: 0.9
  filename: sitemap.xml